basic django server that serves basic home page with dockerfile
justincely/pipsplace pull request #14
Opened 2023-06-12 05:49 UTC by ZachSellman

Man these dockerfiles are messing me up... never seem to find good examples. Everything's working here now finally. Just needs to be run with "docker run -p 8000:8000 <image> " to server running in the container externally.

I figured I'd wait to see if you have significant notes to this push before digging too far into the next steps.

2023-06-13 03:02 UTC, justincely requested changes
Mostly commits to remove, and you'll need to modify the `staticcheck` CI step since this isn't a go project anymore.  I'd recommend replacing it with something like `flake8` or any of the other tools in the ecosystem.

2023-06-13 03:02 UTC, justincely commented on core/core/settings.py
> +DATABASES = {
fine for now - will be good to setup a postgres engine at some point too.  Wont use sqlite3 in production.

2023-06-13 03:02 UTC, justincely commented on core/db.sqlite3
don't commit the DB.

2023-06-13 03:02 UTC, justincely commented
the `core/core` project path is a little weird too, presumably an artifact of the quick start or something.  but can always pull it out later if need be.

2023-06-13 17:27 UTC, ZachSellman commented on core/core/__pycache__/__init__.cpython-310.pyc
Yup, forgot to bring in the boilerplate .gitingore file

2023-06-13 17:29 UTC, ZachSellman commented
Yeah most of this is just the default project files django creates. The core/core path is supposedly standard (based on the courses I've taken at least) where you just provide the name of the project and the django-admin startproject command creates that structure.

2023-06-14 03:23 UTC, justincely approved these changes

2023-06-14 03:23 UTC, merged